/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payment;

import com.formdev.flatlaf.FlatIntelliJLaf;
import dbconnection.DbConnection;
import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Robot;
import java.awt.event.ActionEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import other.AutoCompletion;
import other.Format;
import other.shortcutKey;

/**
 *
 * @author asadj
 */
public class ModPayment extends javax.swing.JDialog {

    /**
     * Creates new form Payment
     */
    static Point rr;
    static Dimension d1;
    static DbConnection db;
    
    static String data[];
    Controller cntrl;
    DefaultTableModel modeltbl;
    List<String> accountname1,accountname2;
    List<Double> amount1,amount2;
    SimpleDateFormat datef=new SimpleDateFormat("dd-MM-yyyy");
    public ModPayment(java.awt.Frame parent, boolean modal,Point rv,Dimension d,String data[],DbConnection db) {
        super(parent, modal);
        initComponents();
        rr=rv;
        d1=d;
        this.data=data;
        this.setLocation(rr);
        this.setSize(d1);
        
        shortcutKey shortcutKey = new shortcutKey(this);
        
        Date date = new Date();
        paymentDate.setDate(date);
                
        new AutoCompletion(nameList);
        
        cntrl=new Controller(db);
        this.db=db;
        
        modeltbl= (DefaultTableModel) tblAccount.getModel();
        tblAccount.setModel(modeltbl);
        
        addbrow(0);
        
        accountname1=new ArrayList<>();
        amount1=new ArrayList<>();
        accountname2=new ArrayList<>();
        amount2=new ArrayList<>();
        txtvchno.setText(data[0]);
        ((JTextField)paymentDate.getDateEditor().getUiComponent()).setText(data[1]);
        cntrl.setData(txtvchno.getText(), lbldebit, lblcredit, accountname1, amount1,accountname2, amount2,modeltbl);
        
        cntrl.fetchaccountsford(nameList);
        
        
        
        paymentDate.getDateEditor().getUiComponent().addFocusListener(new FocusAdapter() {
            public void focusLost(FocusEvent evt){
                try{
                    datef.format(paymentDate.getDate());
                }catch(Exception e){
                    paymentDate.setDate(date);
                }
            }
        });
    }

    public JTable tbl(){
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
               
            }
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(LmodPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
             JTable jTable1=new javax.swing.JTable();
             try {
                UIManager.setLookAndFeel(new FlatIntelliJLaf());
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(LmodPayment.class.getName()).log(Level.SEVERE, null, ex);
            }
         return jTable1;
    }
    
    public void addbrow(int start){
        Object[] obj={" "," "," "," "," "," "};
        for(int i=start;i<start+16;i++)
            modeltbl.addRow(obj);
    }
    public void dltbrow(int start){
        for(int i=start-1;i>=start-16;i--)
            modeltbl.removeRow(i);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnadditem = new javax.swing.JButton();
        btnpayment = new javax.swing.JButton();
        btnreceipt = new javax.swing.JButton();
        btnpurchase = new javax.swing.JButton();
        btnsales = new javax.swing.JButton();
        btnaccdetail = new javax.swing.JButton();
        btnaddaccount = new javax.swing.JButton();
        btnhelp = new javax.swing.JButton();
        btnstocksts = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAccount = tbl();
        jLabel1 = new javax.swing.JLabel();
        txtvchno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        paymentDate = new com.toedter.calendar.JDateChooser();
        amounttype = new javax.swing.JComboBox<>();
        nameList = new javax.swing.JComboBox<>();
        txtamount = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        txtdetail = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btncancle = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        lbldebit = new javax.swing.JLabel();
        lblcredit = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel.setBackground(new java.awt.Color(209, 237, 225));
        jPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel7.setBackground(new java.awt.Color(38, 115, 103));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel2.setText(" >>");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize_window_25px.png"))); // NOI18N
        jLabel11.setToolTipText("Minimize");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close_window_25px.png"))); // NOI18N
        jLabel12.setToolTipText("Close");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Modify Payment Vouchar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1200, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(3, 3, 3))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(561, 561, 561)
                    .addComponent(jLabel8)
                    .addContainerGap(562, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(38, 115, 103));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));

        btnadditem.setBackground(new java.awt.Color(209, 237, 225));
        btnadditem.setText("F3  Add Item");
        btnadditem.setEnabled(false);
        btnadditem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnadditem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadditemActionPerformed(evt);
            }
        });
        btnadditem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnadditemKeyPressed(evt);
            }
        });

        btnpayment.setBackground(new java.awt.Color(209, 237, 225));
        btnpayment.setText("F4  Payment");
        btnpayment.setEnabled(false);
        btnpayment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaymentActionPerformed(evt);
            }
        });
        btnpayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnpaymentKeyPressed(evt);
            }
        });

        btnreceipt.setBackground(new java.awt.Color(209, 237, 225));
        btnreceipt.setText("F5  Receipt");
        btnreceipt.setEnabled(false);
        btnreceipt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnreceipt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnreceiptKeyPressed(evt);
            }
        });

        btnpurchase.setBackground(new java.awt.Color(209, 237, 225));
        btnpurchase.setText("F6  Purchase");
        btnpurchase.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnpurchase.setEnabled(false);
        btnpurchase.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnpurchase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnpurchaseKeyPressed(evt);
            }
        });

        btnsales.setBackground(new java.awt.Color(209, 237, 225));
        btnsales.setText("F7  Sales");
        btnsales.setEnabled(false);
        btnsales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnsales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalesActionPerformed(evt);
            }
        });
        btnsales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnsalesKeyPressed(evt);
            }
        });

        btnaccdetail.setBackground(new java.awt.Color(209, 237, 225));
        btnaccdetail.setText("F8  Account Detail");
        btnaccdetail.setEnabled(false);
        btnaccdetail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnaccdetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnaccdetailKeyPressed(evt);
            }
        });

        btnaddaccount.setBackground(new java.awt.Color(209, 237, 225));
        btnaddaccount.setText("F2  Add Account");
        btnaddaccount.setEnabled(false);
        btnaddaccount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnaddaccount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnaddaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddaccountActionPerformed(evt);
            }
        });
        btnaddaccount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnaddaccountKeyPressed(evt);
            }
        });

        btnhelp.setBackground(new java.awt.Color(209, 237, 225));
        btnhelp.setText("F1  Help");
        btnhelp.setEnabled(false);
        btnhelp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhelpActionPerformed(evt);
            }
        });
        btnhelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnhelpKeyPressed(evt);
            }
        });

        btnstocksts.setBackground(new java.awt.Color(209, 237, 225));
        btnstocksts.setText("F9  Stock Status");
        btnstocksts.setEnabled(false);
        btnstocksts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnstocksts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnstockstsKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnadditem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnpayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnreceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnpurchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnsales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnaccdetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnaddaccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnhelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnstocksts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnhelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnaddaccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadditem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnreceipt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpurchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnaccdetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnstocksts)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblAccount.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        tblAccount.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "D/C", "Account", "Debit", "Credit", "Short Detail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAccount.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblAccount.setGridColor(new java.awt.Color(0, 0, 0));
        tblAccount.setName(""); // NOI18N
        tblAccount.setRowHeight(25);
        tblAccount.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblAccount.getTableHeader().setReorderingAllowed(false);
        tblAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblAccountMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblAccount);
        if (tblAccount.getColumnModel().getColumnCount() > 0) {
            tblAccount.getColumnModel().getColumn(0).setResizable(false);
            tblAccount.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblAccount.getColumnModel().getColumn(1).setResizable(false);
            tblAccount.getColumnModel().getColumn(1).setPreferredWidth(30);
            tblAccount.getColumnModel().getColumn(2).setResizable(false);
            tblAccount.getColumnModel().getColumn(2).setPreferredWidth(400);
            tblAccount.getColumnModel().getColumn(3).setResizable(false);
            tblAccount.getColumnModel().getColumn(3).setPreferredWidth(130);
            tblAccount.getColumnModel().getColumn(4).setResizable(false);
            tblAccount.getColumnModel().getColumn(4).setPreferredWidth(130);
            tblAccount.getColumnModel().getColumn(5).setResizable(false);
            tblAccount.getColumnModel().getColumn(5).setPreferredWidth(230);
        }

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Vouchar No.:");

        txtvchno.setEditable(false);
        txtvchno.setBackground(new java.awt.Color(209, 237, 225));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Date :");

        paymentDate.setDateFormatString("dd-MM-yyyy");

        amounttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D", "C" }));
        amounttype.setNextFocusableComponent(nameList);
        amounttype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                amounttypeItemStateChanged(evt);
            }
        });

        nameList.setEditable(true);
        nameList.setNextFocusableComponent(txtamount);

        txtamount.setNextFocusableComponent(txtdetail);
        txtamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtamountKeyTyped(evt);
            }
        });

        btnadd.setText("ADD");
        btnadd.setNextFocusableComponent(amounttype);
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        txtdetail.setNextFocusableComponent(btnadd);

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btncancle.setText("Cancle");
        btncancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Account Name");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Amount");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Short Detail");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(">>");

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        lbldebit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbldebit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldebit.setText("00.00");
        lbldebit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblcredit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblcredit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcredit.setText("00.00");
        lblcredit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Delete vouchar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amounttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(txtdetail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnadd))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtvchno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnupdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbldebit, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(lblcredit, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncancle)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtvchno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paymentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnadd, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameList, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(amounttype, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btndelete)
                        .addComponent(btnupdate)
                        .addComponent(jButton1))
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbldebit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblcredit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsave)
                        .addComponent(btncancle)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        try {
            Robot rob=new Robot();
            rob.keyPress(KeyEvent.VK_WINDOWS);
            rob.keyPress(KeyEvent.VK_D);
            rob.keyRelease(KeyEvent.VK_WINDOWS);
            rob.keyRelease(KeyEvent.VK_D);
        } catch (AWTException ex) {
            Logger.getLogger(ModPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void btnadditemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadditemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnadditemActionPerformed

    private void btnadditemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnadditemKeyPressed
        ActionEvent ev = null;
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            JOptionPane.showMessageDialog(this,"kom kar se");
        }
    }//GEN-LAST:event_btnadditemKeyPressed

    private void btnpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpaymentActionPerformed

    private void btnpaymentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnpaymentKeyPressed
        ActionEvent ev = null;
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            JOptionPane.showMessageDialog(this,"kom kar se");
        }
    }//GEN-LAST:event_btnpaymentKeyPressed

    private void btnreceiptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnreceiptKeyPressed
        ActionEvent ev = null;
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            JOptionPane.showMessageDialog(this,"kom kar se");
        }
    }//GEN-LAST:event_btnreceiptKeyPressed

    private void btnpurchaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnpurchaseKeyPressed
        ActionEvent ev = null;
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            JOptionPane.showMessageDialog(this,"kom kar se");
        }
    }//GEN-LAST:event_btnpurchaseKeyPressed

    private void btnsalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalesActionPerformed
        
    }//GEN-LAST:event_btnsalesActionPerformed

    private void btnsalesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnsalesKeyPressed
        ActionEvent ev = null;
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            btnsalesActionPerformed(ev);
        }
    }//GEN-LAST:event_btnsalesKeyPressed

    private void btnaccdetailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnaccdetailKeyPressed
        ActionEvent ev = null;
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            JOptionPane.showMessageDialog(this,"kom kar se");
        }
    }//GEN-LAST:event_btnaccdetailKeyPressed

    private void btnaddaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddaccountActionPerformed
        JOptionPane.showMessageDialog(this,"kom kar se");
    }//GEN-LAST:event_btnaddaccountActionPerformed

    private void btnaddaccountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnaddaccountKeyPressed
        ActionEvent ev = null;
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            JOptionPane.showMessageDialog(this,"kom kar se");
        }
    }//GEN-LAST:event_btnaddaccountKeyPressed

    private void btnhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhelpActionPerformed

    private void btnhelpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnhelpKeyPressed
        ActionEvent ev = null;
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            JOptionPane.showMessageDialog(this,"kom kar se");
        }
    }//GEN-LAST:event_btnhelpKeyPressed

    private void btnstockstsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnstockstsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnstockstsKeyPressed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
         if(Double.parseDouble(lblcredit.getText())==Double.parseDouble(lbldebit.getText())){
           cntrl.updatePayment(txtvchno.getText(),datef.format(paymentDate.getDate()),tblAccount,modeltbl,accountname1,amount1,accountname2,amount2);
           this.dispose();
         }else{
             JOptionPane.showMessageDialog(this,"Debit and Credit Amounts should be Equal");
             if(Double.parseDouble(lblcredit.getText())>Double.parseDouble(lbldebit.getText())){
                amounttype.setSelectedIndex(0);
                amounttype.requestFocusInWindow();
                txtamount.setText(Format.ToString(Double.parseDouble(lblcredit.getText())-Double.parseDouble(lbldebit.getText())));
             }
             if(Double.parseDouble(lbldebit.getText())>Double.parseDouble(lblcredit.getText())){
                amounttype.setSelectedIndex(1);
                amounttype.requestFocusInWindow();
                txtamount.setText(Format.ToString(Double.parseDouble(lbldebit.getText())-Double.parseDouble(lblcredit.getText())));
            }
         }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void amounttypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_amounttypeItemStateChanged
        if(amounttype.getSelectedIndex()==0){
            nameList.removeAllItems();
            cntrl.fetchaccountsford(nameList);
            if(Double.parseDouble(lblcredit.getText())>Double.parseDouble(lbldebit.getText())){
                txtamount.setText(Format.ToString(Double.parseDouble(lblcredit.getText())-Double.parseDouble(lbldebit.getText())));
            }
        }
        else if(amounttype.getSelectedIndex()==1){
            nameList.removeAllItems();
            cntrl.fetchaccountsforc(nameList);
            if(Double.parseDouble(lbldebit.getText())>Double.parseDouble(lblcredit.getText())){
                txtamount.setText(Format.ToString(Double.parseDouble(lbldebit.getText())-Double.parseDouble(lblcredit.getText())));
            }
        }
    }//GEN-LAST:event_amounttypeItemStateChanged

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        if(!nameList.getSelectedItem().toString().equals("") && !txtamount.getText().equals("")){
            Object[] data=new Object[6];
            dltbrow(modeltbl.getRowCount());
            data[0]=tblAccount.getRowCount()+1;
            data[1]=amounttype.getSelectedItem();
            data[2]=nameList.getSelectedItem();
            if(amounttype.getSelectedIndex()==0){
                data[3]=txtamount.getText();
                data[4]="";
                lbldebit.setText(Format.ToString(Double.parseDouble(lbldebit.getText())+Double.parseDouble(txtamount.getText())));
            }
            else if(amounttype.getSelectedIndex()==1){
                data[3]="";
                data[4]=txtamount.getText();
                lblcredit.setText(Format.ToString(Double.parseDouble(lblcredit.getText())+Double.parseDouble(txtamount.getText())));
            }
            data[5]=txtdetail.getText();
            modeltbl.addRow(data);
            addbrow(modeltbl.getRowCount()-1);
            nameList.setSelectedIndex(0);
            txtamount.setText("");
            txtdetail.setText("");
            if( !lblcredit.getText().equals("00.00") && Double.parseDouble(lbldebit.getText())>Double.parseDouble(lblcredit.getText()) ){
                amounttype.setSelectedIndex(1);
                txtamount.setText(Format.ToString(Double.parseDouble(lbldebit.getText())-Double.parseDouble(lblcredit.getText())));
            }
            if( !lbldebit.getText().equals("00.00") && Double.parseDouble(lblcredit.getText())>Double.parseDouble(lbldebit.getText())){
                amounttype.setSelectedIndex(0);
                txtamount.setText(Format.ToString(Double.parseDouble(lblcredit.getText())-Double.parseDouble(lbldebit.getText())));
            }
        }else{
            JOptionPane.showMessageDialog(this,"Fill All Details..","Insert..!",2);
        }
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void btncancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancleActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncancleActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int row=tblAccount.getSelectedRow();
        if(row<0){
           JOptionPane.showMessageDialog(this,"Select Row...","Select...",1);
        } 
        else if(row>=tblAccount.getRowCount()-16){
            JOptionPane.showMessageDialog(this,"This Row will not Delete","Delete row",1);
        }
        else{
            int n=JOptionPane.showConfirmDialog(this,"Do you want to delete this?", "Delete?", JOptionPane.YES_NO_OPTION,3);
            if(n==JOptionPane.YES_OPTION){
                if(tblAccount.getValueAt(row, 1).toString().equals("D"))
                    lbldebit.setText(Format.ToString(Double.parseDouble(lbldebit.getText())-Double.parseDouble((String) tblAccount.getValueAt(row, 3))));
                if(tblAccount.getValueAt(row, 1).toString().equals("C"))
                    lblcredit.setText(Format.ToString(Double.parseDouble(lblcredit.getText())-Double.parseDouble((String) tblAccount.getValueAt(row, 4))));
                modeltbl.removeRow(row);
                for(int i=row;i<tblAccount.getRowCount()-16;i++)
                    tblAccount.setValueAt(i+1, i,0);
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        int row=tblAccount.getSelectedRow();
        if(row<0){
           JOptionPane.showMessageDialog(this,"Select Row...","Select...",1);
        } 
        else if(row>=tblAccount.getRowCount()-16){
            JOptionPane.showMessageDialog(this,"This Row will not Update","Update row",1);
        }
        else{
            int n=JOptionPane.showConfirmDialog(this,"Do you want to Update this?", "Update?", JOptionPane.YES_NO_OPTION,3);
            if(n==JOptionPane.YES_OPTION){
                amounttype.setSelectedItem(tblAccount.getValueAt(row, 1));
                nameList.setSelectedItem(tblAccount.getValueAt(row, 2));
                if(tblAccount.getValueAt(row, 1).toString().equals("D")){
                    lbldebit.setText(Format.ToString(Double.parseDouble(lbldebit.getText())-Double.parseDouble((String) tblAccount.getValueAt(row, 3))));
                    txtamount.setText((String) tblAccount.getValueAt(row, 3));
                }
                if(tblAccount.getValueAt(row, 1).toString().equals("C")){
                    lblcredit.setText(Format.ToString(Double.parseDouble(lblcredit.getText())-Double.parseDouble((String) tblAccount.getValueAt(row, 4))));
                    txtamount.setText((String) tblAccount.getValueAt(row, 4));
                }
                txtdetail.setText((String) tblAccount.getValueAt(row, 5));
                modeltbl.removeRow(row);
                for(int i=row;i<tblAccount.getRowCount()-16;i++)
                    tblAccount.setValueAt(i+1, i,0);
            }
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtamountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamountKeyTyped
        char c=evt.getKeyChar();
        if( !(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE || c==KeyEvent.VK_PERIOD)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtamountKeyTyped

    private void tblAccountMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccountMousePressed
        if(evt.getClickCount()==2 && !evt.isConsumed()){
            evt.consume();
            ActionEvent e=null;
            btnupdateActionPerformed(e);
        }
    }//GEN-LAST:event_tblAccountMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int n=JOptionPane.showConfirmDialog(this,"Do you want to delete this?", "Delete?", JOptionPane.YES_NO_CANCEL_OPTION,3);
                if(n==JOptionPane.YES_OPTION){
                    cntrl.dltVch(txtvchno.getText(),accountname1,amount1,accountname2,amount2);
                    JOptionPane.showMessageDialog(null,"Vouchar is Deleted","Deleted",2);
                    this.dispose();
                }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModPayment dialog = new ModPayment(new javax.swing.JFrame(), true,rr,d1,data,db);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> amounttype;
    private javax.swing.JButton btnaccdetail;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnaddaccount;
    private javax.swing.JButton btnadditem;
    private javax.swing.JButton btncancle;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnhelp;
    private javax.swing.JButton btnpayment;
    private javax.swing.JButton btnpurchase;
    private javax.swing.JButton btnreceipt;
    private javax.swing.JButton btnsales;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnstocksts;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblcredit;
    private javax.swing.JLabel lbldebit;
    private javax.swing.JComboBox<String> nameList;
    private com.toedter.calendar.JDateChooser paymentDate;
    private javax.swing.JTable tblAccount;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtdetail;
    private javax.swing.JTextField txtvchno;
    // End of variables declaration//GEN-END:variables
}
